global:
  resolve_timeout: 5m

route:
  group_by: ['alertname', 'cluster', 'service']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 4h
  receiver: 'email_notifications'
  routes:
    - match:
        severity: critical
      receiver: 'email_notifications'

receivers:
- name: 'email_notifications'
  email_configs:
    - to: 'hmdkhkbz@gmail.com'
      send_resolved: true
      from: 'alertmanager@hmdkh.ir'
      smarthost: smtp.hmdkh.ir:587
      auth_username: 'admin'
      auth_password: '$your-smtp-password'
      auth_identity: 'hmdkhkbz@gmail.com'
      text: '{{ template "email.default.text" . }}'
