version: '3.7'

services:
  
  prometheus:
    image: prom/prometheus:v2.28.1
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus-data:/prometheus
    networks:
      - monitor-net
    environment:
      - "TZ=UTC"
    deploy:
      mode: replicated
      replicas: 1
      update_config:
        order: start-first
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - node.hostname == swarm
      resources:
        limits:
          cpus: '2'
          memory: 500M

  # Node Exporter service
  node-exporter:
    image: prom/node-exporter:v1.2.2
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys
